#!/bin/bash
name=$1
repo=$2
username=jacksonStone
githubroot=https://github.com/$username

curl -u "$username" https://api.github.com/user/repos -d "{\"name\":\"$name\"}"

if [ $repo = "none" ]; then
  mkdir $name
  cd $name
  git init
  git remote add origin $githubroot/$name.git
else
  #has repo to copy code from as a base
  git clone $githubroot/$repo $name
  cd $name
  git remote set-url origin $githubroot/$name
  git remote add upstream $githubroot/$name
  git add --all && git commit -m "Initial commit"
  git push -u origin master
fi
